name: Deploy GitHub Page

on:
  push:
    branches:
      - main  # Altere para master se for a sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Etapa 1: Renomear o arquivo HTML para index.html, garantindo que o GitHub Pages o reconheça como página inicial.
      - name: Rename HTML file for GitHub Pages
        run: mv EnglishClasses.html index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # A pasta raiz do repositório
          keep_files: false # Não manter arquivos antigos
          destination_dir: .
